// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHpvDK_zAUHo4Xl1Q_IQnuGvi7SrxaYlw',
    appId: '1:319365862771:web:3a04ddac310de3a1ce6106',
    messagingSenderId: '319365862771',
    projectId: 'online-shop-8d9f9',
    authDomain: 'online-shop-8d9f9.firebaseapp.com',
    storageBucket: 'online-shop-8d9f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0kD0pbLxCbYaLCuHyaQ4S_-qTgDgENbQ',
    appId: '1:319365862771:android:9f7e14587b28289ace6106',
    messagingSenderId: '319365862771',
    projectId: 'online-shop-8d9f9',
    storageBucket: 'online-shop-8d9f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZrk8vvFxxmjc52RTuXeizM9UE0NwKHBE',
    appId: '1:319365862771:ios:6d98b657d91d13d8ce6106',
    messagingSenderId: '319365862771',
    projectId: 'online-shop-8d9f9',
    storageBucket: 'online-shop-8d9f9.appspot.com',
    iosBundleId: 'com.example.onlineGroceyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZrk8vvFxxmjc52RTuXeizM9UE0NwKHBE',
    appId: '1:319365862771:ios:6d98b657d91d13d8ce6106',
    messagingSenderId: '319365862771',
    projectId: 'online-shop-8d9f9',
    storageBucket: 'online-shop-8d9f9.appspot.com',
    iosBundleId: 'com.example.onlineGroceyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHpvDK_zAUHo4Xl1Q_IQnuGvi7SrxaYlw',
    appId: '1:319365862771:web:b037d43a48eaced4ce6106',
    messagingSenderId: '319365862771',
    projectId: 'online-shop-8d9f9',
    authDomain: 'online-shop-8d9f9.firebaseapp.com',
    storageBucket: 'online-shop-8d9f9.appspot.com',
  );
}
